{{- if .Values.netpol.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "azure-resourcemanager-exporter.fullname" . }}
  namespace: {{ template "azure-resourcemanager-exporter.namespace" . }}
  labels: {{ include "azure-resourcemanager-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{ include "azure-resourcemanager-exporter.selectorLabels" . | nindent 6 }}
  policyTypes: {{ toYaml .Values.netpol.policyTypes | nindent 4 }}
  ingress: {{ toYaml .Values.netpol.ingress | nindent 4 }}
  egress: {{ toYaml .Values.netpol.egress | nindent 4 }}
{{- end }}
