{{- $secretHash := include (print $.Template.BasePath "/secret.yaml") . | sha256sum -}}
{{- $configHash := include (print $.Template.BasePath "/config.yaml") . | sha256sum -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kube-pool-manager.fullname" . }}
  namespace: {{ template "kube-pool-manager.namespace" . }}
  labels: {{ include "kube-pool-manager.labels" . | indent 4 }}
spec:

  {{- with .Values.replicas }}
  replicas: {{ . }}
  {{- end }}

  {{- with .Values.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}

  selector:
    matchLabels: {{- include "kube-pool-manager.selectorLabels" . | nindent 6 }}

  minReadySeconds: {{ .minReadySeconds }}
  template:
    metadata:
      labels:
{{ include "kube-pool-manager.selectorLabels" . | indent 8 }}
{{- with .Values.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
      annotations:
        checksum/config: {{ $configHash }}
        checksum/secret: {{ $secretHash }}
{{- with .Values.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}

    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      priorityClassName: {{ .Values.priorityClassName | quote }}

      securityContext: {{ toYaml .Values.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      containers:
        #######################
        # Kube pool manager
        #######################
        - name: kube-pool-manager
          image: {{ include "kube-pool-manager.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}

          securityContext: {{ toYaml .Values.containerSecurityContext | nindent 12 }}
          env:
            - name: CONFIG
              value: /app/config.yaml
            # Instance
            - name: INSTANCE_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INSTANCE_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTANCE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- range $index, $val := .Values.secrets }}
            - name: {{ $index | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "kube-pool-manager.fullname" $ }}
                  key: {{ $index | quote }}
          {{- end }}
          {{- range $name, $value := .Values.env }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- with .Values.extraEnv }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
              name: http-metrics
              protocol: TCP

          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: config
              mountPath: /app
              readOnly: true

      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:  {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "kube-pool-manager.fullname" . }}
